# Generated by Django 2.2.1 on 2020-01-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.TextField(max_length=512)),
                ('Course', models.TextField(max_length=1000)),
            ],
        ),
    ]
