INSERT INTO Hostel_office_department (id, Department, Course) VALUES (30, 'DDU Kaushal Kendras (DDUKK)', 'M.Voc,B.Voc');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (31, 'Department of Applied Chemistry', 'M.Sc,Integrated M.Sc,M.Phil,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (32, 'Department of Applied Economics', 'M.A,M.Phil,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (33, 'Department of Atmospheric Sciences', 'M.Sc,M.Tech,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (34, 'Department of Biotechnology', 'M.Sc,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (35, 'Department of Chemical Oceanography', 'M.Sc,M.Phil,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (36, 'Department of Computer Applications', 'MCA,MSc,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (37, 'Department of Computer Science', 'M.Tech,Ph.D,Test');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (38, 'Department of Electronics', 'M.Sc,M.Tech,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (39, 'Department of Hindi', 'M.A,M.Phil,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (40, 'Department of Instrumentation', 'B.Tech,M.Tech,M.Sc,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (41, 'Department of Marine Biology, Microbiology and Biochemistry', 'M.Sc,M.Tech,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (42, 'Department of Marine Geology and Geophysics', 'M.Sc,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (43, 'Department of Mathematics', 'M.Sc,M.Phil,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (44, 'Department of Physical Oceanography', 'M.Sc,M.Tech,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (45, 'Department of Physics', 'M.Sc,M.Phil,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (46, 'Department of Polymer Science and Rubber Technology', 'B.Tech,M.Tech,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (47, 'Department of Ship Technology', 'B.Tech,M.Tech');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (48, 'Department of Statistics', 'M.Sc,M.Tech,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (49, 'Inter University Centre for IPR Studies (IUCIPRS)', 'LLM,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (50, 'International School of Photonics', 'Integrated M.Sc,Ph.D,M.Tech');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (51, 'National Centre for Aquatic Animal Health (NCAAH)', 'M.Tech,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (52, 'School of Engineering', 'Civil Engg.(B.Tech),Computer Science & Engg.(B.Tech),Electrical and Electronics Engg.(B.Tech),Electronics & Communication Engg.(B.Tech),Information Technology(B.Tech),Mechanical Engg.(B.Tech),Safety & Fire Engg(B.Tech),Civil Engg.(M.Tech),Computer Science & Engg.(M.Tech),Electrical and Electronics Engg.(M.Tech),Electronics & Communication Engg.(M.Tech),Information Technology(M.Tech),Mechanical Engg.(M.Tech),Safety & Fire Engg(M.Tech)');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (53, 'School of Environmental Studies', 'M.Sc,M.Tech,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (54, 'School of Industrial Fisheries', 'M.Sc,M.Phil,Ph.D');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (55, 'School of Legal Studies', 'LLB,LLM');
INSERT INTO Hostel_office_department (id, Department, Course) VALUES (61, 'something', 'asdasd,a,sd,asd,sad');