# Generated by Django 2.2.1 on 2020-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='show_allotment',
            field=models.BooleanField(default=False),
        ),
    ]
