# Generated by Django 2.2.1 on 2020-01-09 19:17

import Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_applications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Photo_upload',
            field=models.FileField(default='settings.MEDIA_ROOT/anonymous.jpg', storage=Application.models.OverwriteStorage(location='E:\\Repositories\\hostels.cusat.ac.in\\media'), upload_to=Application.models.user_directory_path),
        ),
    ]
