# Generated by Django 2.2.1 on 2020-01-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_auto_20200110_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='Date_of_applicaton',
            field=models.DateField(blank=True, null=True),
        ),
    ]
