# Generated by Django 2.2.1 on 2020-01-11 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_applications_date_of_applicaton'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 13, 8, 7, 745143, tzinfo=utc)),
        ),
    ]
