# Generated by Django 2.2.1 on 2020-01-11 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_auto_20200111_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='Date_of_applicaton',
            new_name='Date_of_application',
        ),
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 14, 6, 50, 934713, tzinfo=utc)),
        ),
    ]
