# Generated by Django 2.2.1 on 2020-01-12 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_auto_20200111_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='Pincode',
        ),
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 12, 9, 9, 42, 218364, tzinfo=utc)),
        ),
    ]
