# Generated by Django 2.2.1 on 2020-01-12 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_auto_20200112_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 12, 9, 43, 23, 837151, tzinfo=utc)),
        ),
    ]
