# Generated by Django 2.2.1 on 2020-01-13 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_auto_20200112_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='Pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 13, 7, 15, 51, 881005, tzinfo=utc)),
        ),
    ]
