# Generated by Django 2.2.1 on 2020-01-13 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_auto_20200113_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 13, 7, 16, 39, 869771, tzinfo=utc)),
        ),
    ]
