# Generated by Django 2.2.1 on 2020-01-15 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_auto_20200113_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 8, 52, 48, 17171, tzinfo=utc)),
        ),
    ]
