# Generated by Django 2.2.1 on 2020-01-15 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_auto_20200115_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 9, 4, 14, 354736, tzinfo=utc)),
        ),
    ]
