# Generated by Django 2.2.1 on 2020-01-26 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_auto_20200115_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 13, 44, 42, 430302, tzinfo=utc)),
        ),
    ]
