# Generated by Django 2.2.1 on 2020-01-26 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0014_auto_20200126_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 17, 54, 48, 955463, tzinfo=utc)),
        ),
    ]
