# Generated by Django 2.2.1 on 2020-01-27 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_auto_20200126_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 27, 16, 56, 38, 269062, tzinfo=utc)),
        ),
    ]
