# Generated by Django 2.2.1 on 2020-02-14 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_auto_20200127_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 2, 14, 6, 26, 42, 64259, tzinfo=utc)),
        ),
    ]
