# Generated by Django 2.2.1 on 2020-03-07 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0017_auto_20200214_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 9, 4, 14, 332285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='Department',
            field=models.CharField(choices=[(None, 'Select Department'), ('DDU Kaushal Kendras (DDUKK)', 'DDU Kaushal Kendras (DDUKK)'), ('Department of Applied Chemistry', 'Department of Applied Chemistry'), ('Department of Applied Economics', 'Department of Applied Economics'), ('Department of Atmospheric Sciences', 'Department of Atmospheric Sciences'), ('Department of Biotechnology', 'Department of Biotechnology'), ('Department of Chemical Oceanography', 'Department of Chemical Oceanography'), ('Department of Computer Applications', 'Department of Computer Applications'), ('Department of Computer Science', 'Department of Computer Science'), ('Department of Electronics', 'Department of Electronics'), ('Department of Hindi', 'Department of Hindi'), ('Department of Instrumentation', 'Department of Instrumentation'), ('Department of Marine Biology, Microbiology and Biochemistry', 'Department of Marine Biology, Microbiology and Biochemistry'), ('Department of Marine Geology and Geophysics', 'Department of Marine Geology and Geophysics'), ('Department of Mathematics', 'Department of Mathematics'), ('Department of Physical Oceanography', 'Department of Physical Oceanography'), ('Department of Physics', 'Department of Physics'), ('Department of Polymer Science and Rubber Technology', 'Department of Polymer Science and Rubber Technology'), ('Department of Ship Technology', 'Department of Ship Technology'), ('Department of Statistics', 'Department of Statistics'), ('Inter University Centre for IPR Studies (IUCIPRS)', 'Inter University Centre for IPR Studies (IUCIPRS)'), ('International School of Photonics', 'International School of Photonics'), ('National Centre for Aquatic Animal Health (NCAAH)', 'National Centre for Aquatic Animal Health (NCAAH)'), ('School of Engineering', 'School of Engineering'), ('School of Environmental Studies', 'School of Environmental Studies'), ('School of Industrial Fisheries', 'School of Industrial Fisheries'), ('School of Legal Studies', 'School of Legal Studies'), ('something', 'something'), ('Center for Integrated Studies', 'Center for Integrated Studies'), ('Test', 'Test')], default=0, max_length=255),
        ),
    ]
